name: Build KivyMD APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-setuptools git zip unzip openjdk-8-jdk
          pip install --upgrade pip
          pip install buildozer cython

      - name: Install Android SDK command line tools
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip
          mv cmdline-tools $HOME/android-sdk/cmdline-tools/latest

      - name: Set environment variables
        run: |
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH

      - name: Accept licenses and install packages
        run: |
          sdkmanager --sdk_root=${ANDROID_SDK_ROOT} --licenses
          sdkmanager --sdk_root=${ANDROID_SDK_ROOT} "platform-tools" "platforms;android-29" "build-tools;30.0.3" "ndk;21.3.6528147"

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@main
        with:
          name: kivymd-apk
          path: bin/*.apk
