name: Build KivyMD APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade buildozer cython

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk libffi-dev libssl-dev \
                              libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev \
                              libsdl2-ttf-dev libportmidi-dev libswscale-dev \
                              libavformat-dev libavcodec-dev zlib1g-dev \
                              libgstreamer1.0-dev libmtdev-dev \
                              libgl1-mesa-dev libgles2-mesa-dev xclip

      - name: Download NDK 25b
        run: |
          mkdir -p ~/.buildozer/android/platform
          cd ~/.buildozer/android/platform
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip android-ndk-r25b-linux.zip
          mv android-ndk-r25b android-ndk-r25b-dir

      - name: Set environment variables
        run: |
          echo "ANDROIDNDK=${HOME}/.buildozer/android/platform/android-ndk-r25b-dir" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=${HOME}/.buildozer/android/platform/android-ndk-r25b-dir" >> $GITHUB_ENV

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@main
        with:
          name: myapp-debug.apk
          path: bin/*.apk
