name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker with Buildozer
        run: |
          sudo apt update
          sudo apt install -y docker.io
          docker pull kivy/buildozer

      - name: Build APK inside Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/home/user/app -w /home/user/app kivy/buildozer buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@main
        with:
          name: kivy-apk
          path: bin/*.apk
