name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip zip unzip openjdk-17-jdk
          pip install --upgrade pip
          pip install buildozer cython

      - name: Build APK
        run: |
          echo "sdk.dir=$HOME/.buildozer/android/platform/android-sdk" > local.properties
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@main
        with:
          name: kivy-apk
          path: bin/*.apk
