name: Build KivyMD APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython

      - name: Install system deps
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk libffi-dev libssl-dev \
              libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev \
              libsdl2-ttf-dev libportmidi-dev libswscale-dev \
              libavformat-dev libavcodec-dev zlib1g-dev \
              libgstreamer1.0-dev libmtdev-dev libgl1-mesa-dev \
              libgles2-mesa-dev xclip libjaxb-api-java libjaxb-java libjaxb2-impl-java

      - name: Install Android SDK + cmdline tools
        run: |
          mkdir -p "$HOME/android-sdk/cmdline-tools"
          cd "$HOME/android-sdk/cmdline-tools"
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-9477386_latest.zip
          mv cmdline-tools latest
          mkdir -p "$HOME/.android"
          echo 'count=0' > "$HOME/.android/repositories.cfg"

      - name: Set SDK environment variables
