name: Build KivyMD APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython

      - name: Install system deps
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk libffi-dev libssl-dev \
              libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev \
              libsdl2-ttf-dev libportmidi-dev libswscale-dev \
              libavformat-dev libavcodec-dev zlib1g-dev \
              libgstreamer1.0-dev libmtdev-dev libgl1-mesa-dev \
              libgles2-mesa-dev xclip

      - name: Install Android SDK + cmdline tools
        run: |
          mkdir -p "$HOME/android-sdk/cmdline-tools"
          cd "$HOME/android-sdk/cmdline-tools"
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-9477386_latest.zip
          mv cmdline-tools latest
          mkdir -p "$HOME/.android"
          echo 'count=0' > "$HOME/.android/repositories.cfg"

      - name: Set SDK environment variables
        run: |
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH
          echo "$HOME/android-sdk/tools/bin" >> $GITHUB_PATH

      - name: Accept SDK licenses and install components
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-31" "build-tools;36.0.0" "tools" "platforms;android-31"
        
      - name: Install missing Java dependencies
        run: |
          sudo apt-get install -y libjaxb-api-java libjaxb2-impl-java

      - name: Install AIDL tool and additional components
        run: |
          sdkmanager "build-tools;36.0.0" "ndk;25.0.0" "cmdline-tools;latest"

      - name: Download NDK 25b
        run: |
          mkdir -p ~/.buildozer/android/platform
          cd ~/.buildozer/android/platform
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip android-ndk-r25b-linux.zip
          mv android-ndk-r25b ndk

      - name: Set NDK environment
        run: |
          echo "ANDROIDNDK=$HOME/.buildozer/android/platform/ndk" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$HOME/.buildozer/android/platform/ndk" >> $GITHUB_ENV

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@main
        with:
          name: app-debug.apk
          path: bin/*.apk
