name: Build KivyMD APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python 3.8
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Install dependencies (like Buildozer)
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev build-essential libssl-dev libffi-dev python3-setuptools git
          pip install --upgrade pip
          pip install buildozer

      # Install Android SDK and NDK, AIDL independently
      - name: Install Android SDK and AIDL Independently
        run: |
          # Install Android SDK tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip commandlinetools-linux-8512546_latest.zip -d $HOME/android-sdk
          yes | $HOME/android-sdk/cmdline-tools/bin/sdkmanager --licenses
          # Install specific build tools, platform tools, and NDK
          $HOME/android-sdk/cmdline-tools/bin/sdkmanager "platform-tools" "build-tools;30.0.3" "android-29" "ndk;21.3.6528147"
          # Install AIDL explicitly
          wget https://dl.google.com/android/repository/aidl-linux-x86_64.zip -O $HOME/android-sdk/aidl.zip
          unzip -q $HOME/android-sdk/aidl.zip -d $HOME/android-sdk
          rm $HOME/android-sdk/aidl.zip
          
      # Run buildozer to build the APK
      - name: Build APK
        run: |
          buildozer -v android debug

      # Upload APK artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@main
        with:
          name: kivymd-apk
          path: bin/*.apk
