name: Build KivyMD APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python 3.8
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Install dependencies (like Buildozer)
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev build-essential libssl-dev libffi-dev python3-setuptools git
          pip install --upgrade pip
          pip install buildozer

      # Install Android SDK and NDK
      - name: Install Android SDK and NDK
        run: |
          # Create SDK directory
          mkdir -p $HOME/android-sdk/cmdline-tools

          # Download and unzip command-line tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip commandlinetools-linux-8512546_latest.zip -d $HOME/android-sdk/cmdline-tools

          # Move cmdline-tools into the expected location
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools/* $HOME/android-sdk/cmdline-tools/
          rm -rf $HOME/android-sdk/cmdline-tools/cmdline-tools

          # Accept licenses and install required components
          yes | $HOME/android-sdk/cmdline-tools/bin/sdkmanager --licenses
          $HOME/android-sdk/cmdline-tools/bin/sdkmanager "platform-tools" "build-tools;30.0.3" "android-29" "ndk;21.3.6528147"

          # Set ANDROID_SDK_ROOT environment variable
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV

      # Run buildozer to build the APK
      - name: Build APK
        run: |
          buildozer -v android debug

      # Upload APK artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@main
        with:
          name: kivymd-apk
          path: bin/*.apk
